set -e
true
true
/Users/weeblesthe2nd/miniconda3/envs/spades410/bin/spades-hammer /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/corrected/configs/config.info
/Users/weeblesthe2nd/miniconda3/envs/spades410/bin/python3 /Users/weeblesthe2nd/miniconda3/envs/spades410/share/spades/spades_pipeline/scripts/compress_all.py --input_file /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/corrected/corrected.yaml --ext_python_modules_home /Users/weeblesthe2nd/miniconda3/envs/spades410/share/spades --max_threads 16 --output_dir /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/corrected --gzip_output
true
true
/Users/weeblesthe2nd/miniconda3/envs/spades410/bin/spades-core /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/K21/configs/config.info
/Users/weeblesthe2nd/miniconda3/envs/spades410/bin/spades-core /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/K33/configs/config.info
/Users/weeblesthe2nd/miniconda3/envs/spades410/bin/spades-core /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/K55/configs/config.info
/Users/weeblesthe2nd/miniconda3/envs/spades410/bin/spades-core /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/K77/configs/config.info
/Users/weeblesthe2nd/miniconda3/envs/spades410/bin/python3 /Users/weeblesthe2nd/miniconda3/envs/spades410/share/spades/spades_pipeline/scripts/copy_files.py /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/K77/before_rr.fasta /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/before_rr.fasta /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/K77/assembly_graph_after_simplification.gfa /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/assembly_graph_after_simplification.gfa /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/K77/final_contigs.fasta /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/contigs.fasta /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/K77/first_pe_contigs.fasta /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/first_pe_contigs.fasta /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/K77/strain_graph.gfa /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/strain_graph.gfa /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/K77/scaffolds.fasta /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/scaffolds.fasta /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/K77/scaffolds.paths /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/scaffolds.paths /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/K77/assembly_graph_with_scaffolds.gfa /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/assembly_graph_with_scaffolds.gfa /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/K77/assembly_graph.fastg /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/assembly_graph.fastg /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/K77/final_contigs.paths /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/contigs.paths
true
/Users/weeblesthe2nd/miniconda3/envs/spades410/bin/python3 /Users/weeblesthe2nd/miniconda3/envs/spades410/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/scaffolds.fasta --misc_dir /Users/weeblesthe2nd/Desktop/genome_section_report/spadesoutput/misc --threshold_for_breaking_scaffolds 3
true
